# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shervin/workspace/qt_ws/Toys/Robust_IRL_TOY

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shervin/workspace/qt_ws/Toys/Robust_IRL_TOY

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shervin/workspace/qt_ws/Toys/Robust_IRL_TOY/CMakeFiles /home/shervin/workspace/qt_ws/Toys/Robust_IRL_TOY/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shervin/workspace/qt_ws/Toys/Robust_IRL_TOY/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Robust_IRL_TOY

# Build rule for target.
Robust_IRL_TOY: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Robust_IRL_TOY
.PHONY : Robust_IRL_TOY

# fast build rule for target.
Robust_IRL_TOY/fast:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/build
.PHONY : Robust_IRL_TOY/fast

src/DETree.o: src/DETree.cpp.o
.PHONY : src/DETree.o

# target to build an object file
src/DETree.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/DETree.cpp.o
.PHONY : src/DETree.cpp.o

src/DETree.i: src/DETree.cpp.i
.PHONY : src/DETree.i

# target to preprocess a source file
src/DETree.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/DETree.cpp.i
.PHONY : src/DETree.cpp.i

src/DETree.s: src/DETree.cpp.s
.PHONY : src/DETree.s

# target to generate assembly for a file
src/DETree.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/DETree.cpp.s
.PHONY : src/DETree.cpp.s

src/MCHMM.o: src/MCHMM.cpp.o
.PHONY : src/MCHMM.o

# target to build an object file
src/MCHMM.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/MCHMM.cpp.o
.PHONY : src/MCHMM.cpp.o

src/MCHMM.i: src/MCHMM.cpp.i
.PHONY : src/MCHMM.i

# target to preprocess a source file
src/MCHMM.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/MCHMM.cpp.i
.PHONY : src/MCHMM.cpp.i

src/MCHMM.s: src/MCHMM.cpp.s
.PHONY : src/MCHMM.s

# target to generate assembly for a file
src/MCHMM.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/MCHMM.cpp.s
.PHONY : src/MCHMM.cpp.s

src/Observation.o: src/Observation.cpp.o
.PHONY : src/Observation.o

# target to build an object file
src/Observation.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Observation.cpp.o
.PHONY : src/Observation.cpp.o

src/Observation.i: src/Observation.cpp.i
.PHONY : src/Observation.i

# target to preprocess a source file
src/Observation.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Observation.cpp.i
.PHONY : src/Observation.cpp.i

src/Observation.s: src/Observation.cpp.s
.PHONY : src/Observation.s

# target to generate assembly for a file
src/Observation.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Observation.cpp.s
.PHONY : src/Observation.cpp.s

src/RIRL.o: src/RIRL.cpp.o
.PHONY : src/RIRL.o

# target to build an object file
src/RIRL.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/RIRL.cpp.o
.PHONY : src/RIRL.cpp.o

src/RIRL.i: src/RIRL.cpp.i
.PHONY : src/RIRL.i

# target to preprocess a source file
src/RIRL.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/RIRL.cpp.i
.PHONY : src/RIRL.cpp.i

src/RIRL.s: src/RIRL.cpp.s
.PHONY : src/RIRL.s

# target to generate assembly for a file
src/RIRL.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/RIRL.cpp.s
.PHONY : src/RIRL.cpp.s

src/Sample.o: src/Sample.cpp.o
.PHONY : src/Sample.o

# target to build an object file
src/Sample.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Sample.cpp.o
.PHONY : src/Sample.cpp.o

src/Sample.i: src/Sample.cpp.i
.PHONY : src/Sample.i

# target to preprocess a source file
src/Sample.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Sample.cpp.i
.PHONY : src/Sample.cpp.i

src/Sample.s: src/Sample.cpp.s
.PHONY : src/Sample.s

# target to generate assembly for a file
src/Sample.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Sample.cpp.s
.PHONY : src/Sample.cpp.s

src/Sampler.o: src/Sampler.cpp.o
.PHONY : src/Sampler.o

# target to build an object file
src/Sampler.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Sampler.cpp.o
.PHONY : src/Sampler.cpp.o

src/Sampler.i: src/Sampler.cpp.i
.PHONY : src/Sampler.i

# target to preprocess a source file
src/Sampler.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Sampler.cpp.i
.PHONY : src/Sampler.cpp.i

src/Sampler.s: src/Sampler.cpp.s
.PHONY : src/Sampler.s

# target to generate assembly for a file
src/Sampler.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Sampler.cpp.s
.PHONY : src/Sampler.cpp.s

src/Timer.o: src/Timer.cpp.o
.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i
.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s
.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/data.o: src/data.cpp.o
.PHONY : src/data.o

# target to build an object file
src/data.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/data.cpp.o
.PHONY : src/data.cpp.o

src/data.i: src/data.cpp.i
.PHONY : src/data.i

# target to preprocess a source file
src/data.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/data.cpp.i
.PHONY : src/data.cpp.i

src/data.s: src/data.cpp.s
.PHONY : src/data.s

# target to generate assembly for a file
src/data.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/data.cpp.s
.PHONY : src/data.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/process.o: src/process.cpp.o
.PHONY : src/process.o

# target to build an object file
src/process.cpp.o:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/process.cpp.o
.PHONY : src/process.cpp.o

src/process.i: src/process.cpp.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.cpp.i:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/process.cpp.i
.PHONY : src/process.cpp.i

src/process.s: src/process.cpp.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.cpp.s:
	$(MAKE) -f CMakeFiles/Robust_IRL_TOY.dir/build.make CMakeFiles/Robust_IRL_TOY.dir/src/process.cpp.s
.PHONY : src/process.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Robust_IRL_TOY"
	@echo "... src/DETree.o"
	@echo "... src/DETree.i"
	@echo "... src/DETree.s"
	@echo "... src/MCHMM.o"
	@echo "... src/MCHMM.i"
	@echo "... src/MCHMM.s"
	@echo "... src/Observation.o"
	@echo "... src/Observation.i"
	@echo "... src/Observation.s"
	@echo "... src/RIRL.o"
	@echo "... src/RIRL.i"
	@echo "... src/RIRL.s"
	@echo "... src/Sample.o"
	@echo "... src/Sample.i"
	@echo "... src/Sample.s"
	@echo "... src/Sampler.o"
	@echo "... src/Sampler.i"
	@echo "... src/Sampler.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

